### PR TITLE
Allow Node.js 18

### PR DESCRIPTION
**Pull request by ted-pulsen**
**Summary**

Allow and test on Node.js 18

This PR fixes/implements the following **bugs/features**

* [x] Bug #116 

Explain the **motivation** for making this change. What existing problem does the pull request solve?

To prevent the warning from `npm` upon installation.

**Test plan (required)**

CI has been updated to test on Node.js 18 as well

### CODE REVIEW

**Comment by ted-pulsen** [comment]
I had to update ts-node as well in order to allow for the test suite to run

**Comment by regevbr** [comment]
Thanks @ted-pulsen. I think that updating ts-node will cause the node 6 tests to fail (which I still need to support sadly) so please revert it

**Comment by ted-pulsen** [comment]
I see, no worries. I got the test suite to run and pass locally on node 18.6.0 provided that ts-node was updated.

**Comment by regevbr** [comment]
fixed in #118, will publiush a new version now

**Comment by regevbr** [comment]
released in 4.3.0 thanks!

**Pull request closed without merging**
